name: Deploy to Azure Web App - rest-module-daniela

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build
          yarn test

      - name: Create deployment zip
        run: zip -r deployment.zip .

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v2
        with:
          name: deployment-artifact
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v2
        with:
          name: deployment-artifact

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rest-module-daniela'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8DE151800EBC4E3E8EF2E14F078CA2ED }}
          package: deployment.zip
